# fly.toml app configuration
app = "crm-machine-001"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[[services]]
  protocol = "tcp"
  internal_port = 5000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[checks]
  [checks.http]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/"
