# fly.toml app configuration file generated for crm-app-mandasatechnologies on 2026-02-27T12:21:26+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crm-app-mandasatechnologies'
primary_region = 'lax'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
