# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: fm2_lJPECAAAAAAAAGXdxBCVOmL/csJEEy0KlYOYeRQqwrVodHRwczovL2FwaS5mbHkuaW8vdjGUAJLOAAEnHR8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDz+OYqaEAIR59xZcaXZxNAI9KTN7ku5A0eRtoVbgDacGPW8OVC8hNoX16b+9f4thSfszBxJyrp4al9bm4bETjwRrpVTSHnqjQYSiIra5pGRcEZYyI65Nm4mUnE0J1LkCDVTnTir++Utyu94k98myDO6guT3OAZ+8xJzNpEGuIfRFxnrqLKE9GH2vgmHiMQgeeadyiW3akQWcpEc1zdc19NN14KOL8bFLLIYCNlp+7k=,fm2_lJPETjwRrpVTSHnqjQYSiIra5pGRcEZYyI65Nm4mUnE0J1LkCDVTnTir++Utyu94k98myDO6guT3OAZ+8xJzNpEGuIfRFxnrqLKE9GH2vgmHiMQQ3T8cGFmn8VcTATuMzyvLosO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5pumTVzmm6Z0sXzgABCkAKkc4AAQpADMQQsVcDTzj+Jkho3W5UD2xmMsQgwUomC7W+rEEB71mwV1relV26dAOsquYp570+OVtv9VY=,fo1_YttmjoavZqDpi_FYLZEFyNsiv6pTH4GL2GPpfZn6Vw8