name: Deploy to Fly Machine

# Trigger on pushes to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Fly CLI
      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      # Step 3: Login to Fly
      - name: Fly auth
        run: flyctl auth token FlyV1 fm2_lJPECAAAAAAAAGXdxBC1LSL2ep7qgWrDDmdRnaJwwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAAEnHR8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDxsDw/t3W/Ys8fRuMxcqCI986FOW9UxSd8gVnKXX/0S6EhrYkrcfxroum9yT7Ta2CTHHYxatGLJTo5+tMXETtiVaZXQZ/qt59fOlIS7G7lDT7MnzYx0xLJlaBAbTXXIWNwThp57AttqQJ1aMT305JWmAogftWTTaJsWzlHWeR15hZMilZobQSChrHLZRg2SlAORgc4Aw/10HwWRgqdidWlsZGVyH6J3Zx8BxCDoGX6aZ3KQgm18ap6RjgmtNJn4eP/zKzNtH7EjSoMLJQ==,fm2_lJPETtiVaZXQZ/qt59fOlIS7G7lDT7MnzYx0xLJlaBAbTXXIWNwThp57AttqQJ1aMT305JWmAogftWTTaJsWzlHWeR15hZMilZobQSChrHLZRsQQ16heqkWWbZv/spt2o6ZUksO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5pZ2KVzwAAAAElX4CzF84AAQpACpHOAAEKQAzEEPfZtPuDDpteEt5qxKnIt5/EIGKTy5WAbEiMRq+UJ0M0s2h/nqIRwEc5Dl6bXiJgzGRQ

      # Step 4: Deploy Docker image to your machine
      - name: Deploy to Fly Machine
        env:
          FLY_API_TOKEN: FlyV1 fm2_lJPECAAAAAAAAGXdxBC1LSL2ep7qgWrDDmdRnaJwwrVodHRwczovL2FwaS5mbHkuaW8vdjGWAJLOAAEnHR8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDxsDw/t3W/Ys8fRuMxcqCI986FOW9UxSd8gVnKXX/0S6EhrYkrcfxroum9yT7Ta2CTHHYxatGLJTo5+tMXETtiVaZXQZ/qt59fOlIS7G7lDT7MnzYx0xLJlaBAbTXXIWNwThp57AttqQJ1aMT305JWmAogftWTTaJsWzlHWeR15hZMilZobQSChrHLZRg2SlAORgc4Aw/10HwWRgqdidWlsZGVyH6J3Zx8BxCDoGX6aZ3KQgm18ap6RjgmtNJn4eP/zKzNtH7EjSoMLJQ==,fm2_lJPETtiVaZXQZ/qt59fOlIS7G7lDT7MnzYx0xLJlaBAbTXXIWNwThp57AttqQJ1aMT305JWmAogftWTTaJsWzlHWeR15hZMilZobQSChrHLZRsQQ16heqkWWbZv/spt2o6ZUksO5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5pZ2KVzwAAAAElX4CzF84AAQpACpHOAAEKQAzEEPfZtPuDDpteEt5qxKnIt5/EIGKTy5WAbEiMRq+UJ0M0s2h/nqIRwEc5Dl6bXiJgzGRQ
        run: |
          flyctl deploy \
            --remote-only \
            --image nginx:alpine \
            --app crm-machine-001
